KS-3-2 used """
Slavikus1/KotlinSprint1 pull request #12
Opened 2024-03-12 17:33 UTC by Slavikus1

2024-03-13 15:45 UTC, ievetrovdev requested changes

2024-03-13 15:45 UTC, ievetrovdev commented on src/main/kotlin/lesson3/lesson3_task2.kt
> +    val familyName = "Андреева"
Проинициализированные данные мы принимаем за "сущность". Пока что не забегаем вперед, но такое дублирование переменных не очень правильный тон (представь, что таких смен фамилий будет 50 шт условно). Поэтому мы исходные переменные оставляем как есть, но потом перезаписываем в них данные. Поэтому распечатываем сначала то, что есть, а затем меняем данные в переменных и отображаем снова.

2024-03-13 15:45 UTC, ievetrovdev commented on src/main/kotlin/lesson3/lesson3_task2.kt
> +        [$nextFamilyName $name $surname, $age2.]
В задаче и далее в других [] подразумевает формат, их печатать не нужно

2024-03-13 16:25 UTC, Slavikus1 commented on src/main/kotlin/lesson3/lesson3_task2.kt
> +    val familyName = "Андреева"
Понял

2024-03-15 08:31 UTC, ievetrovdev approved these changes
Все четко!

2024-03-15 08:37 UTC, merged