KS-4-4 googled how to use odd and even numbers in kotlin
Slavikus1/KotlinSprint1 pull request #19
Opened 2024-03-17 15:19 UTC by Slavikus1

2024-03-18 07:17 UTC, ievetrovdev requested changes

2024-03-18 07:17 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task4.kt
> +    var numberOfWorkoutDay = 1
Зачем сначала создавать переменные, а потом уже задавать нужные значения, нет ведь никакой необходимости

2024-03-18 07:17 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task4.kt
> +    absAndArmsExercises = numberOfWorkoutDay in (1..100).filter { number -> number % 2 != 0 }
Зачем такие сложности, проще же сразу число проверять на четность. Можно сделать это 1 раз,а дальше уже булеву переменную инвертировать где нужно. Еще принято булевы значения начинать с is (например isEvenDay)

2024-03-18 09:26 UTC, Slavikus1 commented on src/main/kotlin/lesson4/lesson4_task4.kt
> +    absAndArmsExercises = numberOfWorkoutDay in (1..100).filter { number -> number % 2 != 0 }
Всё исправил)

2024-03-18 16:18 UTC, ievetrovdev requested changes

2024-03-18 16:18 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task4.kt
> +    val isOddDay = (numberOfWorkoutDay % 2) != 0
почти верно, кроме того что дважды считаешь, если хочешь две переменные то проще было бы `val isOddDay = !isEvenDay`.

2024-03-18 16:18 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task4.kt
> +        |Упражнения для рук: $isOddDay
А вообще можно сразу здесь писать `|Упражнения для рук: $!isEvenDay `

2024-03-19 07:37 UTC, ievetrovdev approved these changes

2024-03-19 14:56 UTC, merged