KS-4-5 task with ship's expedition.
Slavikus1/KotlinSprint1 pull request #20
Opened 2024-03-18 10:42 UTC by Slavikus1

2024-03-18 16:28 UTC, ievetrovdev requested changes

2024-03-18 16:28 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task5.kt
> +    val currentNumberOfCrew = answerAboutCrew!!.toInt()
Предлагаю использовать более свежую функцию чтения с консоли readln(). Она не требует обработки null, а делает приведение всего входящего к строке под капотом. 

Дело в том, что readLine() по умолчанию возвращает тип String?. Далее ты приводишь к Инту toInt(), используя !!, что приведет к падению приложения. Более правильно использовать операторы безопасного вызова типа let или .?. Об этом будет в уроке про нулябельность. Но пока предлагаю использовать readln()

2024-03-18 16:28 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task5.kt
> +        (isCurrentWeatherConditions != true || isCurrentWeatherConditions == true)
Не совсем понимаю зачем эта строка, если она всегда возвращает true.

2024-03-18 16:28 UTC, ievetrovdev commented on src/main/kotlin/lesson4/lesson4_task5.kt
> +    if ((isCurrentDamage == false) &&
Булевы параметры с которым сравниваешь тоже лучше вынести в константы, так как они не изменяемы и легко переиспользуемы. Так же это упростит чтение

2024-03-18 16:30 UTC, Slavikus1 commented on src/main/kotlin/lesson4/lesson4_task5.kt
> +        (isCurrentWeatherConditions != true || isCurrentWeatherConditions == true)
> Не совсем понимаю зачем эта строка, если она всегда возвращает true.

строка 31?

2024-03-20 06:51 UTC, ievetrovdev approved these changes
Да, все хорошо

2024-03-20 14:27 UTC, merged