KS-5-3 Lottery random task
Slavikus1/KotlinSprint1 pull request #23
Opened 2024-03-18 16:46 UTC by Slavikus1

2024-03-19 07:39 UTC, ievetrovdev requested changes

2024-03-19 07:39 UTC, ievetrovdev commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +        (firstChoosen == rightFirstNumber) &&
А что будет, если пользователь введет выигрышные числа в обратном порядке?)

2024-03-19 07:39 UTC, ievetrovdev commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +                (secondChoosen == rightSecondNumber) -> println("Вы выиграли утешительный приз!")
Из-за этих лишних отступов тяжелее читать, убери пожалуйста

2024-03-19 18:04 UTC, Slavikus1 commented on src/main/kotlin/lesson5/lesson5_task3.kt
> +                (secondChoosen == rightSecondNumber) -> println("Вы выиграли утешительный приз!")
Убрал отступы из условий, но когда юзанул ctrl alt l, система сама сделала пробел

2024-03-20 06:57 UTC, ievetrovdev approved these changes

2024-03-20 14:27 UTC, merged