KS-8-4 replace ingredient
Slavikus1/KotlinSprint1 pull request #39
Opened 2024-03-30 14:14 UTC by Slavikus1

2024-03-31 06:24 UTC, ievetrovdev requested changes

2024-03-31 06:24 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task4.kt
> +            val index = ingredientsArray.indexOf(i)
Прочитай подробнее про indexOf, при его использовании не нужен цикл

2024-04-01 07:30 UTC, ievetrovdev requested changes

2024-04-01 07:30 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task4.kt
> +        val getIndex = ingredientsArray.indexOf(usersChoice)
Хорош, только момент, нет необходимости второй раз использовать indexOf, можно сразу записать в переменную и использовать в обоих местах

2024-04-02 06:43 UTC, ievetrovdev requested changes

2024-04-02 06:43 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task4.kt
> +    if (index in ingredientsArray.indices) {
В предыдущей раз же все правильно было кроме двойного использования indexOf. Зачем снова менять и использовать in. в этот if надо только добавить проверку index if (index != -1){

2024-04-02 15:42 UTC, Slavikus1 commented on src/main/kotlin/lesson8/lesson8_task4.kt
> +    if (index in ingredientsArray.indices) {
> n. в этот if надо только добавить проверку index if

просто в похожей задаче вы говорили что можно через in проверять. Я и подумал что -1 это маг число, а через in как-то солидно.

2024-04-03 06:50 UTC, ievetrovdev approved these changes
Можно делать и через in, но только ни когда используешь indexOf. Получается ты одно и тоже дважды сделал.

2024-04-03 15:05 UTC, merged