KS-8-5 arrayOf Ingredients with adding in list ony by one
Slavikus1/KotlinSprint1 pull request #40
Opened 2024-03-31 15:17 UTC by Slavikus1

2024-04-01 07:32 UTC, ievetrovdev requested changes

2024-04-01 07:32 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task5.kt
> +        arrayOfIngredients += entered
Смотри, изначально был создан массив с одним строковым элементом. Конструкция += фактически каждый раз пересоздает массив, копируя все предыдущие элементы в новый. Довольно затратная процедура. Согласно ТЗ нам надо с самого начала создать массив с определенным количеством ячеек.

2024-04-02 06:48 UTC, ievetrovdev requested changes

2024-04-02 06:48 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task5.kt
> +    for (i in ingredientsArray) {
Идея правильная, но много лишних переменных. index и numberOfIngredient можно убрать если использовать цикл с диапазоном for (i in 0..ingredientsArray.size - 1) {

2024-04-02 06:48 UTC, ievetrovdev commented on src/main/kotlin/lesson8/lesson8_task5.kt
> +        val ingredient = readln()
Тут можно опустить переменную и сразу присвоить из readln

2024-04-02 16:06 UTC, Slavikus1 commented on src/main/kotlin/lesson8/lesson8_task5.kt
> +    for (i in ingredientsArray) {
> (i in 0..ingredientsArray.size - 1)

Очень интересно получилось. Спасибо!

2024-04-03 06:48 UTC, ievetrovdev approved these changes

2024-04-03 15:05 UTC, merged