KS-1-5 tried to complete the task in a right way!
Slavikus1/KotlinSprint1 pull request #5
Opened 2024-03-09 13:59 UTC by Slavikus1

2024-03-10 12:37 UTC, ievetrovdev requested changes

2024-03-10 12:37 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +fun main(){
Так как это 5 задача ("со звездочкой") не по уровню урока, то и решение должно быть более продвинутым (может потребовать дополнительного ресерча). 

Твой текущий вывод не похож на тот, который требуется по примеру.

Попробуй еще использовать оператор остатка от деления

2024-03-10 12:37 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +fun main(){
Есть нюансы по пробелам. В Idea есть автоформатирование кода: Находясь в файле Ctrl+Alt+L (для windows) или ⌥+⌘+L (для osx). Старайся применять автоформат перед каждым коммитом.

2024-03-10 12:37 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +   println(minutes)
Формат вывода был описан как
[часы:минуты:секунды]
Будь внимательнее к требованиям.
В реальных проектах, даже если тебе кажется что правильно по-твоему, лучше сделать как в требованиях. В идеале, кончено, на этапе получения задачки от заказчика нужно уточнить корректность, но в нашем случае необязательно, так как ошибки нам только на пользу.

2024-03-10 12:37 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +   val minutes = seconds/60
Чтобы снизить риск ошибок, предлагаю еще вынести 60 (и 3600) в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-03-10 12:37 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +   val rest = 0.8 * 60
Также неизвестно откуда взялось число 0.8. Все должно высчитываться программно

2024-03-10 20:04 UTC, Slavikus1 commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +   val minutes = seconds/60
константа это прям const val? или просто val? Я правильно понял, что магические числа - те которые я никак не объявлял (они как будто из потолка)? И из-за них другим будет тяжелее работать с таким кодом?

2024-03-11 13:22 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +   val minutes = seconds/60
да, ты все правильно понял) константы это `const val` и синтаксис у них отличается от переменных, они должны быть названы заглавными буквами с нижними подчеркиваниями)

2024-03-11 13:23 UTC, ievetrovdev requested changes

2024-03-11 13:23 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    println("Гагарин провел в космосе [01:$spaceMin:0$spaceSec]")
попробуй использовать `String.format` для того чтобы избавиться от дополнительных нулей

2024-03-11 13:23 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val findMinutes = 60
вынести в константы

2024-03-11 19:54 UTC, Slavikus1 commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val findMinutes = 60
По какому принципу понимать какие данные выносить именно в константы? Тут например, мы вынесли эти две переменные потому что это наши основные множители и делители?

2024-03-12 07:18 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +    val findMinutes = 60
когда число встречается в коде более 1 раза и оно не приходит в функцию снаружи, то его можно выносить в константу) иначе есть вероятность забыть поменять число в одном из мест использования

2024-03-12 07:19 UTC, ievetrovdev requested changes

2024-03-12 07:19 UTC, ievetrovdev commented on src/main/kotlin/lesson1/lesson1_task5.kt
> +//    println(spaceHours)
а зачем здесь столько закомментированных принтов? давай их удалим

2024-03-15 06:11 UTC, ievetrovdev approved these changes

2024-03-15 08:35 UTC, merged