KS-13-4;
Slavikus1/KotlinSprint1 pull request #64
Opened 2024-04-30 13:22 UTC by Slavikus1

2024-04-30 14:35 UTC, ievetrovdev requested changes

2024-04-30 14:35 UTC, ievetrovdev commented on src/main/kotlin/lesson13/lesson13_task4.kt
> +    val phoneNumber: Long? = null,
По ТЗ телефон не может быть нулл

2024-04-30 14:35 UTC, ievetrovdev commented on src/main/kotlin/lesson13/lesson13_task4.kt
> +    val contactsList = mutableListOf<DirectoryListBook>(
По ТЗ объект телефонной книги должен заполнятся пользователем. И для введеный им телефон проверятся на нулл

2024-04-30 16:49 UTC, Slavikus1 commented on src/main/kotlin/lesson13/lesson13_task4.kt
> +    val contactsList = mutableListOf<DirectoryListBook>(
> По ТЗ объект телефонной книги должен заполнятся пользователем. И для введеный им телефон проверятся на нулл

Здравствуйте! Не понимаю что требуется... конструктор класса и так же заполняется пользователем.. нужно вызывать одновременно несколько объектов класса, как в прошлом задании?

2024-05-01 08:27 UTC, ievetrovdev commented on src/main/kotlin/lesson13/lesson13_task4.kt
> +    val contactsList = mutableListOf<DirectoryListBook>(
Имеется ввиду заполнение с консоли, через readln(). Так введеный телефон можно проверить является ли это телефоном

2024-05-01 08:28 UTC, ievetrovdev requested changes
опять же в классе phoneNumber не нулевой

2024-05-02 14:25 UTC, ievetrovdev requested changes

2024-05-02 14:25 UTC, ievetrovdev commented on src/main/kotlin/lesson13/lesson13_task4.kt
> +    var phoneNumber: String = readln(),
Это вообще очень плохая практика в конструкторе писать функцию, просто оставь val phoneNumber: String

2024-05-02 14:25 UTC, ievetrovdev commented on src/main/kotlin/lesson13/lesson13_task4.kt
> +    val listToCheck = mutableListOf<DirectoryListBook>(
Тут просто инициализируй пустой список

2024-05-02 14:25 UTC, ievetrovdev commented on src/main/kotlin/lesson13/lesson13_task4.kt
> +    for (i in listToCheck){
здесь уже в цикле while проси параметры от пользователя и записывай в переменные.
потом проводи проверку этих переменных по условия (не нулевой телефон)
если все верно создавай из них объект DirectoryListBook и записывай в список

2024-05-03 07:18 UTC, ievetrovdev approved these changes
Да, теперь отлично

2024-05-06 15:20 UTC, merged