Ks 2 2 employees
Slavikus1/KotlinSprint1 pull request #7
Opened 2024-03-10 11:18 UTC by Slavikus1

Случайно слил файл main (причем сразу после того, как написал что задача была легкой. Классика кармы, учусь смирению)

2024-03-10 13:31 UTC, ievetrovdev requested changes

2024-03-10 13:31 UTC, ievetrovdev commented on src/main/kotlin/Main.kt
> +    println(++a)
давай тогда его удалим из ПРа) удаление тоже можно коммитить

2024-03-10 13:31 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task2.kt
> +    val salaryOfSeniors = 50 * 30000
Следует сначала объявить переменные из ТЗ, а только потом заниматься вычислениями. Сейчас эти значения выглядят как хардкод и такую программу невозможно масштабировать и поставлять в нее другие значения для расчета.

2024-03-10 13:31 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task2.kt
> +    val averageSalary = totalExpenses / 80
80 тоже непонятно откуда взяли

2024-03-10 13:31 UTC, ievetrovdev commented
Несколько комментариев по оформлению пулл реквеста:
 - Префикс проекта с названием и номером урока задачи следует прописывать в названии пулл реквеста. Например, "KS-1-1 сделал то-то".
 - Название ветки также должно содержать префикс проекта с номером урока и задачи, чтобы они все были уникальны и в них можно было легко ориентироваться. Слова в названии веток разделяются дефисами. Например, “KS-1-1-create-smth”.

2024-03-10 20:56 UTC, Slavikus1 commented on src/main/kotlin/Main.kt
> +    println(++a)
Вроде удалил... удалил же?

2024-03-11 19:52 UTC, ievetrovdev requested changes

2024-03-11 19:52 UTC, ievetrovdev commented on src/main/kotlin/Main.kt
> +    println(++a)
нет, попробуй удалить весь файл)

2024-03-11 19:52 UTC, ievetrovdev commented on src/main/kotlin/lesson2/lesson2_task2.kt
> +    val salaryOfJuniors = 20000
а здесь по заданию все отлично

2024-03-12 07:20 UTC, ievetrovdev approved these changes

2024-03-12 08:28 UTC, merged