KS-14-5; не понимаю как сделать с id
Slavikus1/KotlinSprint1 pull request #71
Opened 2024-05-11 16:38 UTC by Slavikus1

2024-05-12 05:44 UTC, ievetrovdev requested changes
Описане классов верное

2024-05-12 05:44 UTC, ievetrovdev commented on src/main/kotlin/lesson14/lesson14_task5.kt
> +        messages.add(Message(messageText, messageAuthor, messageId = ))
ИД можно брать из размера списка 
`messages.size`
Еще как вариант можешь создать отдельную переменную, и инкрементить ее. Но вариант выше красивее

2024-05-12 05:44 UTC, ievetrovdev commented on src/main/kotlin/lesson14/lesson14_task5.kt
> +    private val childMessages: MutableList<ChildMessage> = mutableListOf(),
Если хочешь то можно попробовать с 1 списком, но это на твое усмотрение

2024-05-12 05:44 UTC, ievetrovdev commented on src/main/kotlin/lesson14/lesson14_task5.kt
> +    fun addThreadMessage(parentMessageId: Int) {}
тут так же по аналогии с обычными сообщениями, только не забудь про другие параметры

2024-05-16 07:23 UTC, ievetrovdev requested changes

2024-05-16 07:23 UTC, ievetrovdev commented on src/main/kotlin/lesson14/lesson14_task5.kt
> +    fun addThreadMessage(messageText: String, messageAuthor: String, parentMessageId: Int = messages.size) {
parentMessageId это уже не сгенирировные число, а ид сообщения к которому относится, например у тебя 2  сообщения с ид 1 и 2 и ты хочешь ответить на второе, значит parentMessageId надо передать 2.

2024-05-16 07:23 UTC, ievetrovdev commented on src/main/kotlin/lesson14/lesson14_task5.kt
> +        val groupById = messages.groupBy {it.messageId}
Группировать можно по ид 
```
messages.groupBy {
            if (it is ChildMessage)
                it.parentMessageId
            else
                it.id
        }
```

2024-05-27 17:09 UTC, Slavikus1 commented on src/main/kotlin/lesson14/lesson14_task5.kt
> +        val groupById = messages.groupBy {it.messageId}
Не понимаю как обратиться к группам и как вывести печать дочерних сообщений под родительскими

2024-05-28 07:24 UTC, ievetrovdev requested changes

2024-05-28 07:24 UTC, ievetrovdev commented on src/main/kotlin/lesson14/lesson14_task5.kt
> +        val groupById = messages.groupBy {it.messageId}
После такой группировки у тебя будет мапа с сообщниями одного ид. Начинаешь выводить каждую такую группу и если сообщение ChildMessage то делаешь отступ
```
val threadMap: Map<Int, List<Message>> = messages.groupBy {
            if (it is ChildMessage)
                it.parentMessageId
            else
                it.id
        }

        threadMap.forEach { (_, messageList) ->
            messageList.forEach { message ->
                val tab = if (message is ChildMessage) "\t" else ""
                println("$tab${message.id}. ${message.author}: ${message.text}")
            }
        }
```

2024-08-05 13:34 UTC, ievetrovdev approved these changes

2024-08-07 09:16 UTC, merged