KS-15-2; создал абстрактный класс, два класса потомка и реализацию се…
Slavikus1/KotlinSprint1 pull request #72
Opened 2024-05-27 16:59 UTC by Slavikus1

…рвера

2024-05-27 22:38 UTC, ievetrovdev requested changes

2024-05-27 22:38 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task2.kt
> +        if (data is Temperature){
Добавь учет кейса, если передали неизвестный тип данных. Можешь при желании переписать через when, будет красивее выглядеть (но это уже не обязательно)

2024-05-28 20:41 UTC, ievetrovdev requested changes

2024-05-28 20:41 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task4.kt
> +package lesson15
Файл попал по ошибке. Что делать?
в данном пулл реквесте надо:
- переключиться в ветку текущего ПР
- удалить лишний файл с задачей (физически из проекта)
- сделать коммит (с изменением удаления)
- прислать ссылку на этот же пулл реквест снова в бот

2024-05-28 20:42 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task4.kt
> +package lesson15
ПР отклоняется, так как соблюдение Git-flow не менее важная часть работы.

2024-05-29 13:54 UTC, ievetrovdev requested changes

2024-05-29 13:54 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task4.kt
> +package lesson15
Судя по правкам, ты не удалил, а только добавил пустую строку https://github.com/Slavikus1/KotlinSprint1/pull/72/commits/a5ced6dfcd5f247b8b62d930a8cbd5e83f432e77

2024-05-29 14:04 UTC, Slavikus1 commented on src/main/kotlin/lesson15/lesson15_task4.kt
> +package lesson15
> Судя по правкам, ты не удалил, а только добавил пустую строку [a5ced6d](https://github.com/Slavikus1/KotlinSprint1/commit/a5ced6dfcd5f247b8b62d930a8cbd5e83f432e77)

удалил файл через рефактор (переключившись на ветку задачи), а пробел поставил потому что не мог выбрать файл для комит энд пуш без изменений

2024-05-31 18:56 UTC, merged