KS-15-4; создал интерфейс и родительский класс
Slavikus1/KotlinSprint1 pull request #74
Opened 2024-05-29 14:52 UTC by Slavikus1

2024-05-29 19:01 UTC, ievetrovdev requested changes

2024-05-29 19:01 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task4.kt
> +    fun searchDetails() {
Так как в задачах мы стремимся к реальным решениям, то логика поиска должна быть реализована уже в классах.

2024-05-31 13:52 UTC, Slavikus1 commented on src/main/kotlin/lesson15/lesson15_task4.kt
> +    fun searchDetails() {
> Так как в задачах мы стремимся к реальным решениям, то логика поиска должна быть реализована уже в классах.

Имеется в виду что реализовать метод нужно в классе, а не в интерфейсе?

2024-05-31 21:20 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-05-31 21:20 UTC, ievetrovdev commented on src/main/kotlin/lesson15/lesson15_task4.kt
> +    fun searchDetails() {
Да

2024-06-01 10:08 UTC, merged