KS-17-3; создал геттеры, но столкнулся с проблемой разности типов. Ес…
Slavikus1/KotlinSprint1 pull request #83
Opened 2024-07-04 15:50 UTC by Slavikus1

…ли явно прописываю типы, он все равно предлагает сменить их на any

2024-07-05 07:10 UTC, ievetrovdev requested changes

2024-07-05 07:10 UTC, ievetrovdev commented on src/main/kotlin/lesson17/lesson17_task3.kt
> +class Folder(){
По хорошему еще добавить бы в конструктор обявление переменных

2024-07-05 07:10 UTC, ievetrovdev commented on src/main/kotlin/lesson17/lesson17_task3.kt
> +        get() = if (activeSecretFlag) field = "скрытая папка" else field
в field ничего не нужно присваивать, это же геттер

2024-07-06 10:04 UTC, Slavikus1 commented on src/main/kotlin/lesson17/lesson17_task3.kt
> +class Folder(){
> По хорошему еще добавить бы в конструктор обявление переменных

Правильно ли я понимаю что это для того, чтобы было комфортнее создавать объект класса используя конструктор, а не обращаясь к переменным из созданного объекта?

2024-07-06 13:43 UTC, ievetrovdev commented on src/main/kotlin/lesson17/lesson17_task3.kt
> +class Folder(){
Да, все верно. Удобнее сразу задать переменные при создании объекта

2024-07-06 13:43 UTC, ievetrovdev approved these changes

2024-07-14 18:26 UTC, merged