KS-18-2; subtyping
Slavikus1/KotlinSprint1 pull request #87
Opened 2024-07-18 08:52 UTC by Slavikus1

2024-07-18 21:37 UTC, ievetrovdev requested changes

2024-07-18 21:37 UTC, ievetrovdev commented on src/main/kotlin/lesson18/lesson18_task2.kt
> +import kotlin.random.Random
Рекомендую пользоваться котлиновской экстеншен функцией для получения рандомного числа. Она поаккуратнее и избавимся от лишнего импорта

2024-07-18 21:37 UTC, ievetrovdev commented on src/main/kotlin/lesson18/lesson18_task2.kt
> +open class Dice {
Поле под кол-во граней нужно обозначить прям тут, например    abstract val number: Int. Передача этого параметра в конструктор - ломает логику реализации наследников. Они должны быть с указанным кол-во граней, без возможности это изменить извне.

2024-07-18 21:37 UTC, ievetrovdev commented on src/main/kotlin/lesson18/lesson18_task2.kt
> +    private val sides: Int = 4,
6?

2024-07-19 17:51 UTC, Slavikus1 commented on src/main/kotlin/lesson18/lesson18_task2.kt
> +open class Dice {
> ломает логику реализации наследников

по факту)

2024-07-19 18:22 UTC, Slavikus1 commented on src/main/kotlin/lesson18/lesson18_task2.kt
> +import kotlin.random.Random
> 

а почему не приветствуется лишний импорт?

2024-07-23 20:44 UTC, ievetrovdev requested changes
Все хорошо, только импорт убрать осталось

2024-07-23 20:44 UTC, ievetrovdev commented on src/main/kotlin/lesson18/lesson18_task2.kt
> +import kotlin.random.Random
Дополнительный код тянется, который можно не тянуть

2024-07-23 20:44 UTC, ievetrovdev commented on src/main/kotlin/lesson18/lesson18_task2.kt
> +import kotlin.random.Random
Давай уберем import

2024-07-26 23:36 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-07-29 10:02 UTC, merged